### ISSUE TITLE
Log Signer hanging when select statement gets stuck

### ISSUE THREAD

**Issue by paulmattei** [google/trillian#1605] opened 2019-05-16 09:16 UTC
Hi trillian team, we're encountering some oddities with a particular log. We see the log_signer processing speedily right until a select statement gets stuck and the log_signer halts. The select eventually times out at `300s` per our connection config. Once the query times out, the following goroutine information is dumped to the log, a rollback occurs, and the log_signer begins processing again.It's unclear why the log_signer cruises along right until it hits a wall.

```
I0515 22:11:15.082392       1 log_operation_manager.go:454] Group run completed in 0.02 seconds: 3 succeeded, 0 failed, 3 items processed
I0515 22:11:15.110065       1 sequencer.go:472] 1045204392378480099: sequenced 1 leaves, size 210937358, tree-revision 24322870
I0515 22:11:15.110078       1 log_operation_manager.go:435] 1045204392378480099: processed 1 items in 0.02 seconds (43.67 qps)
I0515 22:11:15.110091       1 log_operation_manager.go:454] Group run completed in 0.02 seconds: 3 succeeded, 0 failed, 1 items processed
I0515 22:11:15.156972       1 sequencer.go:472] 1045204392378480099: sequenced 1 leaves, size 210937359, tree-revision 24322871
I0515 22:11:15.156985       1 log_operation_manager.go:435] 1045204392378480099: processed 1 items in 0.02 seconds (45.00 qps)
I0515 22:11:15.156994       1 log_operation_manager.go:454] Group run completed in 0.02 seconds: 3 succeeded, 0 failed, 1 items processed
W0515 22:12:15.177265       1 tree_storage.go:224] Failed to get merkle subtrees: context deadline exceeded
W0515 22:12:15.177352       1 tree_storage.go:429] TX rollback error: sql: transaction has already been committed or rolled back, stack:
goroutine 2329070 [running]:
runtime/debug.Stack(0xc000222380, 0x10a5e20, 0xc000142950)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/trillian/storage/mysql.(*treeTX).rollbackInternal(0xc000176280, 0xf94dd0, 0xc000af2368)
	/go/src/github.com/google/trillian/storage/mysql/tree_storage.go:429 +0x5c
github.com/google/trillian/storage/mysql.(*treeTX).Close(0xc000176280, 0x0, 0x0)
	/go/src/github.com/google/trillian/storage/mysql/tree_storage.go:440 +0x82
github.com/google/trillian/storage/mysql.(*mySQLLogStorage).ReadWriteTransaction(0xc00040e690, 0x10b9080, 0xc0009d22a0, 0xc0007941e0, 0xc000412e70, 0x10a5e20, 0xc0002b4e30)
	/go/src/github.com/google/trillian/storage/mysql/log_storage.go:280 +0x164
github.com/google/trillian/log.Sequencer.IntegrateBatch(0x10b92c0, 0xc00013aee8, 0x10ac1e0, 0x187f360, 0x10bc600, 0xc00040e690, 0xc0007eacf0, 0x10b93c0, 0xc0005a83c0, 0x10b9080, ...)
	/go/src/github.com/google/trillian/log/sequencer.go:323 +0x26e
github.com/google/trillian/server.(*SequencerManager).ExecutePass(0xc00036a090, 0x10b9080, 0xc0009d22a0, 0xe814fdb6d65b5e3, 0xc00041e280, 0xc00039c930, 0x100, 0x0)
	/go/src/github.com/google/trillian/server/sequencer_manager.go:87 +0x5d8
github.com/google/trillian/server.(*logOperationExecutor).run.func1(0xc000d34130, 0xc000148100, 0x10b9040, 0xc00018fec0, 0xc000d34140, 0xc000d34128, 0xc000d34148)
	/go/src/github.com/google/trillian/server/log_operation_manager.go:423 +0x14d
created by github.com/google/trillian/server.(*logOperationExecutor).run
	/go/src/github.com/google/trillian/server/log_operation_manager.go:413 +0x23a
W0515 22:12:15.177364       1 tree_storage.go:442] Rollback error on Close(): sql: transaction has already been committed or rolled back
E0515 22:12:15.177373       1 log_operation_manager.go:425] ExecutePass(1045204392378480099) failed: failed to integrate batch for 1045204392378480099: 0e814fdb6d65b5e3: failed to fetch nodes: failed to get Merkle nodes: context deadline exceeded
E0515 22:13:06.473410       1 log_operation_manager.go:425] ExecutePass(1045204392378480099) failed: failed to integrate batch for 1045204392378480099: 1045204392378480099: Sequencer failed to load sequenced batch: 1045204392378480099: Sequencer failed to dequeue leaves: Error 1205: Lock wait timeout exceeded; try restarting transaction
```

Here's a corresponding slow query. To note here is `Rows_examined: 49094613` which seems very high because this tree has 200M certificates stored.

```
# Time: 190515 20:00:02
# User@Host: logsigner[logsigner] @  [10.96.12.104]
# Thread_id: 153017879  Schema: oak  QC_hit: No
# Query_time: 300.001089  Lock_time: 0.000023  Rows_sent: 1  Rows_examined: 49094613
# Rows_affected: 0  Bytes_sent: 1327
use db;
SET timestamp=1557950402;
SELECT x.SubtreeId, x.MaxRevision, Subtree.Nodes
 FROM (
 	SELECT n.SubtreeId, max(n.SubtreeRevision) AS MaxRevision
	FROM Subtree n
	WHERE n.SubtreeId IN ('\0\0\0\0\d','\0\0\0\0\','\0\0\0\0','\0\0\0\0') AND
	 n.TreeId = 1045204392378480099 AND n.SubtreeRevision <= 24319872
	GROUP BY n.TreeId, n.SubtreeId
 ) AS x
 INNER JOIN Subtree 
 ON Subtree.SubtreeId = x.SubtreeId 
 AND Subtree.SubtreeRevision = x.MaxRevision 
 AND Subtree.TreeId = 1045204392378480099;
/rdsdbbin/mysql/bin/mysqld, Version: 10.3.8-MariaDB-log (Source distribution). started with:
Tcp port: 3306  Unix socket: /tmp/mysql.sock
Time		    Id Command	Argument
```

Below you'll find slowquery we hacked apart with `hex` and `unhex`

```
EXPLAIN SELECT hex(x.SubtreeId), x.MaxRevision, Subtree.Nodes from (SELECT n.SubtreeId, max(n.SubtreeRevision) AS MaxRevision FROM Subtree n WHERE n.SubtreeId IN (unhex('000000000C92A6'), unhex('000000000C92'), unhex('000000000C'), unhex('00000000')) AND n.TreeId = 1045204392378480099 AND n.SubtreeRevision <= 2431987200 GROUP BY n.TreeId, n.SubtreeId) as x INNER JOIN Subtree ON Subtree.SubtreeId = x.SubtreeId AND Subtree.SubtreeRevision = x.MaxRevision AND Subtree.TreeId = 1045204392378480099;
+------+-------------+------------+--------+---------------+---------+---------+---------------------------------+--------+---------------------------------------+
| id   | select_type | table      | type   | possible_keys | key     | key_len | ref                             | rows   | Extra                                 |
+------+-------------+------------+--------+---------------+---------+---------+---------------------------------+--------+---------------------------------------+
|    1 | PRIMARY     | <derived2> | ALL    | NULL          | NULL    | NULL    | NULL                            | 719802 | Using where                           |
|    1 | PRIMARY     | Subtree    | eq_ref | PRIMARY       | PRIMARY | 269     | const,x.SubtreeId,x.MaxRevision |      1 |                                       |
|    2 | DERIVED     | n          | range  | PRIMARY       | PRIMARY | 269     | NULL                            | 959736 | Using where; Using index for group-by |
+------+-------------+------------+--------+---------------+---------+---------+---------------------------------+--------+---------------------------------------+
3 rows in set (0.008 sec)
```

When debugging these queries, one thing that is difficult for us is that inflight queries from `show processlist` contain binary data which doesn't copy/paste well. Would the trillian team be open to generating the queries in `unhex` form if the performance overhead isn't too high?

A final thing to note is that our sequencer config contains `-sequencer_interval=20ms -num_sequencers=20 -batch_size=10000`. Is the value `sequencer_interval=20ms` a good value for a 200M+ cert log? This same configuration on a larger log does not cause issues like this.

We deployed trillian commit 4831a21 this afternoon and since then have seen ~100 messages spaced `50s` apart.

`Sequencer failed to load sequenced batch: 1045204392378480099: Sequencer failed to dequeue leaves: Error 1205: Lock wait timeout exceeded; try restarting transaction"`

Starting May 2nd on commit 07c5829 we began seeing the following with a sharp increase today.

`failed to integrate batch`

Specifically

`failed to integrate batch for 1045204392378480099: 0e814fdb6d65b5e3: failed to fetch nodes: failed to get Merkle nodes: (invalid connection|context deadline exceeded|context canceled)`

and

`failed to integrate batch for 1045204392378480099: 1045204392378480099: Sequencer failed to load sequenced batch: 1045204392378480099: Sequencer failed to dequeue leaves: Error 1205: Lock wait timeout exceeded; try restarting transaction`

Not the invalid connection is presumably because we have a readTimeout on our DB conn

The database connection string is

`-mysql_uri=user:pass@tcp(mysql:3306)/db?readTimeout=28s&max_statement_time=25`

weird  then that we're getting `invalid connection` rather than `max_statement_time exceeded`

**Comment by pavelkalinnikov** [comment] 2019-05-16 09:23
Originated here: https://github.com/google/trillian/issues/1188#issuecomment-492878267

**Comment by pgporada** [comment] 2019-05-16 16:59
Thanks for opening this @paulmattei.

**Comment by pavelkalinnikov** [comment] 2019-05-22 15:22
https://github.com/google/trillian/pull/1598

**Comment by AlCutter** [comment] 2019-05-22 16:14
#1595 is somewhat related to this

I'd try reducing that batch size too - 10k could result in a pretty large transaction to chew through if there's a backlog in the queue.

**Comment by paulmattei** [comment] 2019-05-23 14:20
> Hi all!

Here are some tests that have been run:
*Test 1*
```
Tree size: ~280 million
Batch size: 200
Interval: 250ms
Load: 480rps
Result: At first each sequencer run took on average 0.3 seconds but after 5-10 minutes I started seeing each sequencer run taking ~16 seconds, the delay being the database select query Jacob pasted earlier. 
```
*Test 2*
```
Tree size: ~280 million
Batch size: 100
Interval: 100ms
Load: 480rps
Result: Same result as test 1. The ~16 second queries brought sequencing down to a crawl that could not keep up with the 480rps load.
Result after turning off load: After a backlog of unsequenced rows from Test 2, I turned off the load of new entries which allowed for the sequencer to process with no potential contention. The select queries still took about 16 seconds to complete and sequencing remained very slow.
```
*Test 3*
```
Tree size: ~280 million
Batch size: 1000
Interval: 20ms
Load: 300rps
Result: Each sequencer run completes in about 15 seconds averaging 65qps of sequencing.
```

In general, it looks like when our batch size gets too low the query is still expensive enough that our qps makes it not able to keep up with the submissions. We had kept our interval low because by the time one sequencing run is done we need to be starting the next.

A batch size of 10,000 was working ok at first but now we see the select query from the sequencer hang up for over 300 seconds until our max_statement_time kills it, then subsequent runs of the sequencer will run successfully until another hangs. We have been able to keep up with the submission rate ok so far, but it's not a desirable behavior.

After a few of those tests against our test log we decided to try batch size 1000 and 250ms on on the log we are seeing the problems.

*Test 4* (against most affected log):
```
Tree size: 228 million
Batch size: 1000
Interval: 250ms
Load: ~30 qps live traffic from Let's Encrypt CA
Result: The select query still takes over 300 seconds until killed by max_statement_time and then subsequent runs will catch us back up on sequencing then another query will hang for 300 seconds. So basically the same behavior as what we see with 10,000 batch size.
```
All of the logs we have tested seem to run many sequencer runs very quickly then get hung up on one for varying amounts of time then proceed to run fast again.
<sub>[View in Slack](https://gtrillian.slack.com/archives/C5E5P19A6/p1558567168041100)</sub>

**Comment by Martin2112** [comment] 2019-06-04 11:29
Can you give #1650 a try on your test system? I'm not sure how much effect it will have as we can't reproduce the exact situation you seem to have. However, the query cost seemed considerably lower in our tests.

**Comment by pgporada** [comment] 2019-10-23 17:13
@Martin2112 
As of Trillian commit `c82424a1` we're still seeing the following slow query log and the same rollback issue as the original post.
```
# Thread_id: 61321599  Schema: oak  QC_hit: No
# Query_time: 62.002765  Lock_time: 0.000021  Rows_sent: 0  Rows_examined: 12424090
# Rows_affected: 0  Bytes_sent: 249
SET timestamp=1571834890;
SELECT x.SubtreeId, x.MaxRevision, Subtree.Nodes
 FROM (
 	SELECT n.TreeId, n.SubtreeId, max(n.SubtreeRevision) AS MaxRevision
	FROM Subtree n
	WHERE n.SubtreeId IN ('\0\0\0\0','\0\0\0\0!','\0\0\0\0!^','\0\0\0\0!^;') AND
	 n.TreeId = 1045204392378480099 AND n.SubtreeRevision <= 30608569
	GROUP BY n.TreeId, n.SubtreeId
 ) AS x
 INNER JOIN Subtree 
 ON Subtree.SubtreeId = x.SubtreeId 
 AND Subtree.SubtreeRevision = x.MaxRevision 
 AND Subtree.TreeId = x.TreeId
 AND Subtree.TreeId = 1045204392378480099;
```

Here's some recent results from the metric added by #1656.
![trillian-log-signer-stats-1](https://user-images.githubusercontent.com/2382565/67417165-223f8b00-f596-11e9-91b2-9282d30b9cbc.png)
![trillian-log-signer-stats-2](https://user-images.githubusercontent.com/2382565/67417166-223f8b00-f596-11e9-9714-6152b81981d6.png)

**Comment by Martin2112** [comment] 2019-10-28 08:14
We may have to think again then but I'm not sure what else can be done. The metric shows a reasonable batch size so I don't think that's the problem.

**Comment by pavelkalinnikov** [comment] 2019-10-28 23:49
Probably a bonkers idea, but why does the query put `n.SubtreeId` in front of `n.TreeId` in `WHERE` clause and the `JOIN` condition? To be completely perfectionist about it, and to exclude any possibility of it being inconveniently not optimized, I would reorder the fields to match the schema.

**Comment by pavelkalinnikov** [comment] 2019-10-29 00:33
@pgporada:

In the experiments above the size of the sequencer batch and/or the frequency of sequencing is not really the thing that influences the speed of the query. The data that the above mentioned query is trying to read is the right edge of the tree, which consists of 4 "subtrees" (aka tiles) regardless of the parameters (the number of tiles only depends on the current tree size).

It looks like the query tries to scan too many `Subtree` rows. That is because the subtrees have revisions. Specifically, the tile at the top of the tree can have way too many revisions, because each tree modification creates a new one.

Just to confirm my understanding:

- Do you consistently see this query being slow for big trees? Or it fires rarely and at random points in time?
- Do you see this problem when you run this query manually from command line?

On the "sawtooth" graph here https://github.com/google/trillian/issues/1188#issuecomment-461929943, I think the moments in time where the sequencer latency drops is when a certain top-level tile stops being updated (because its subtree is complete), and a "fresh" one is started. This shouldn't happen often, you would see small fluctuations with a period of 256, a bigger one every 256^2 leaves, and major ones each 256^3 leaves.

Now, the question is: Why does this query do a full scan of revisions, even though it's asked to find MAX? According to https://mariadb.com/kb/en/library/minmax-optimization/, this should not happen.

**Comment by pavelkalinnikov** [comment] 2019-10-29 02:11
Hm, even a simple query like below results in a full scan:

```
> explain SELECT n.TreeId, n.SubtreeId, max(n.SubtreeRevision) AS MaxRevision FROM Subtree n WHERE n.TreeId=1464502757925370067 and n.SubtreeId='' AND n.SubtreeRevision <= 32 GROUP BY n.TreeId, n.SubtreeId;
+------+-------------+-------+-------+---------------+---------+---------+------+------+-----------------------------------------------------------+
| id   | select_type | table | type  | possible_keys | key     | key_len | ref  | rows | Extra                                                     |
+------+-------------+-------+-------+---------------+---------+---------+------+------+-----------------------------------------------------------+
|    1 | SIMPLE      | n     | range | PRIMARY       | PRIMARY | 269     | NULL |   32 | Using where; Using index; Using temporary; Using filesort |
+------+-------------+-------+-------+---------------+---------+---------+------+------+-----------------------------------------------------------+
1 row in set (0.001 sec)
```

**Comment by AlCutter** [comment] 2020-03-04 14:26
Hey Phil, since this issue has been quiet since end of Oct I'm guessing you've found a workaround?
I'll close this for now, but feel free to re-open if need be!

**Closed by AlCutter** 2020-03-04 14:26 UTC
Labels: help wanted, operations
